Controllers/LearnController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SaveUs.Controllers
{
    public class LearnController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }

        public IActionResult Consent()
        {
            return View();
        }
    }
}

Controllers/MonitorController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;
using SaveUs.Models.Monitor;
using static SaveUs.Models.Monitor.Locations;

namespace SaveUs.Controllers
{
    public class MonitorController : Controller
    {
        public IActionResult Index()
        {
            LocationLists model = new LocationLists();
            var locations = new List<Locations>()
            {
                new Locations(1, "Bhubaneswar","Bhubaneswar, Odisha", 20.296059, 85.824539),
                new Locations(2, "Hyderabad","Hyderabad, Telengana", 17.387140, 78.491684),
                new Locations(3, "Bengaluru","Bengaluru, Karnataka", 12.972442, 77.580643)
            };
            model.LocationList = locations;
            return View(model);
        }

        public IActionResult Test()
        {
            return View();
        }

    }
}

Controllers/StoryController.cs
using System;
using System.Collections.Generic;
using System.Linq;
using System.Threading.Tasks;
using Microsoft.AspNetCore.Mvc;

namespace SaveUs.Controllers
{
    public class StoryController : Controller
    {
        public IActionResult Index()
        {
            return View();
        }
    }
}

Views/Shared/_Layout.cshtml
@using Microsoft.AspNetCore.Identity
@inject SignInManager<IdentityUser> SignInManager
@inject UserManager<IdentityUser> UserManager

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - SaveUs</title>
    @*<link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
        <link rel="stylesheet" href="~/css/site.css" />*@
    <link href="https://fonts.googleapis.com/css?family=Oxygen:300,400" rel="stylesheet">
    <link href="https://fonts.googleapis.com/css?family=Source+Sans+Pro:400,600,700" rel="stylesheet">

    <!-- Animate.css -->
    <link rel="stylesheet" href="~/css/animate.css">
    <!-- Icomoon Icon Fonts-->
    <link rel="stylesheet" href="~/css/icomoon.css">
    <!-- Bootstrap  -->
    <link rel="stylesheet" href="~/css/bootstrap.css">

    <!-- Magnific Popup -->
    <link rel="stylesheet" href="~/css/magnific-popup.css">

    <!-- Flexslider  -->
    <link rel="stylesheet" href="~/css/flexslider.css">

    <!-- Theme style  -->
    <link rel="stylesheet" href="~/css/style.css">

    <!-- Modernizr JS -->
    <script src="~/js/modernizr-2.6.2.min.js"></script>
</head>
<body>
    <div class="fh5co-loader"></div>
    <div id="page">
        <nav class="fh5co-nav" role="navigation">
            <div class="container-wrap">
                <div class="top-menu">
                    <div class="row">
                        <div class="col-xs-2">
                            <div id="fh5co-logo"><a asp-controller="Home" asp-action="Index">SaveUs</a></div>
                        </div>
                        <div class="col-xs-10 text-right menu-1">
                            <ul>
                                <li class="active"><a asp-controller="Home" asp-action="Index">Home</a></li>
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <li class="has-dropdown">
                                        <a asp-controller="SaveMe" asp-action="Index">SaveMe</a>
                                        <ul class="dropdown">
                                            <li><a asp-controller="SaveMe" asp-action="Register">Request Beacon</a></li>
                                            
                                        </ul>
                                    </li>
                                }
                                else
                                {
                                    <li><a asp-controller="SaveMe" asp-action="Index">SaveMe</a></li>
                                }
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <li><a asp-controller="SaveMe" asp-action="Register">Order Beacon</a></li>
                                    <li><a asp-controller="Monitor" asp-action="Index">Monitor</a></li>
                                    
                                        <li><a asp-controller="Monitor" asp-action="Test">Test Monitor</a></li>
                                    
                                }
                                <li class="has-dropdown">
                                    <a asp-controller="Learn" asp-action="Index">Learn</a>
                                    <ul class="dropdown">
                                        <li><a asp-controller="Learn" asp-action="Index">Gender Based Violence</a></li>
                                        <li><a asp-controller="Learn" asp-action="Consent">Consent</a></li>
                                    </ul>
                                </li>
                                <li class="has-dropdown">
                                    <a asp-controller="Story" asp-action="Index">Stories</a>
                                    <ul class="dropdown">
                                        <li><a href="#">Dedeker’s Story</a></li>
                                        <li><a href="#">Nicole's Story</a></li>
                                        <li><a href="#">Samantha's Story</a></li>
                                    </ul>
                                </li>

                                @*<li><a href="contact.html">Contact</a></li>*@
                                @if (SignInManager.IsSignedIn(User))
                                {
                                    <li>
                                        <a asp-area="Identity" asp-page="/Account/Manage/Index" title="Manage">Hello @User.Identity.Name!</a>
                                    </li>
                                    <li>
                                        <form class="form-inline" asp-area="Identity" asp-page="/Account/Logout" asp-route-returnUrl="@Url.Action("Index", "Home", new { area = "" })">
                                            <button type="submit" class="btn btn-link text-dark">Logout</button>
                                        </form>
                                    </li>
                                }
                                else
                                {
                                    <li>
                                        <a class="text-dark" asp-area="Identity" asp-page="/Account/Register">Register</a>
                                    </li>
                                    <li>
                                        <a class="text-dark" asp-area="Identity" asp-page="/Account/Login">Login</a>
                                    </li>
                                }
                            </ul>
                        </div>
                    </div>

                </div>
            </div>
        </nav>

        <div class="container-wrap">
            @RenderBody()
        </div>
        <div class="container-wrap">
            <footer id="fh5co-footer" role="contentinfo">
                <div class="row">
                    &copy; 2020 - SaveUs - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                </div>
            </footer>
        </div>
        <script src="~/js/jquery.min.js"></script>
        <!-- jQuery Easing -->
        <script src="~/js/jquery.easing.1.3.js"></script>
        <!-- Bootstrap -->
        <script src="~/js/bootstrap.min.js"></script>
        <!-- Waypoints -->
        <script src="~/js/jquery.waypoints.min.js"></script>
        <!-- Flexslider -->
        <script src="~/js/jquery.flexslider-min.js"></script>
        <!-- Magnific Popup -->
        <script src="~/js/jquery.magnific-popup.min.js"></script>
        <script src="~/js/magnific-popup-options.js"></script>
        <!-- Counters -->
        <script src="~/js/jquery.countTo.js"></script>
        <!-- Main -->
        <script src="~/js/main.js"></script>

        @RenderSection("Scripts", required: false)
</body>
</html>